# Generated by Django 4.1 on 2023-10-17 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
